<a href="https://colab.research.google.com/github/Prakuljn/Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# numpy -> it is a open source library that is used for sintific calculation
# why numpy is beeter than list ?
# 1. numpy (homogeneous data type ),list(hetrogeneous data type)
# 2. numpy (time less consuption ), list (more time consuption)
# 3. numpy (less memory consume), list(more memory consuption )
# 4. numpy has more functionality than list


In [9]:
import numpy as np

In [10]:
a=[1,45,89,90]
type (a)

list

In [12]:
b=np.array(a)
print(b)
type(b)

[ 1 45 89 90]


numpy.ndarray

In [15]:
c=[[1,2,3],[4,5,6],[7,8,9]]
d=np.array(c)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
print("total rows and column", d.shape)
print("total elements", d.size)
print("total dimension", d.ndim)

total rows and column (3, 3)
total elements 9
total dimension 2


In [19]:
b.ndim

1

In [21]:
# how to create user define array

a=[]
size= int (input("enter array size: "))
for i in range (size):
  val= int (input ("enter values: "))
  a.append(val)
b=np.array(a)

enter array size: 3
enter values: 3 
enter values: 4
enter values: 5


In [22]:
b

array([3, 4, 5])

In [23]:
b*3

array([ 9, 12, 15])

In [27]:
# pre defined function in python
# 1. zeros()--> it will create an array in which all values will be 0
a=np.zeros(3)
print(a)
b=np.zeros((3,4))
print(b)

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [30]:
# 2. ones --> it will create an array in which all the values will be 1
a=np.ones(3)
print(a)
b=np.ones((3,4))
print(b)

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
# 3. eye() --> it will create an array in which the diagonal positional elements value will be one and rest of are zero
a=np.eye(3,3) # it create by default dimension will be 2
a=np.eye(3,3) # it create by default dimension will be 2
# a=np.eye(3,3)  number(rows) == number (column) it means symettric matrix
print(a)
b=np.eye(3,4)     # number(rows) != number (column) it means asymettric matrix
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [35]:
# 4. diag()--> it will create an array that will set diagonal positional custum element by us
a = np.diag([11,2,3,4000]) # it default create symmetric matrix
a

array([[  11,    0,    0,    0],
       [   0,    2,    0,    0],
       [   0,    0,    3,    0],
       [   0,    0,    0, 4000]])