<a href="https://colab.research.google.com/github/Prakuljn/Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy -> it is a open source library that is used for sintific calculation
# why numpy is beeter than list ?
# 1. numpy (homogeneous data type ),list(hetrogeneous data type)
# 2. numpy (time less consuption ), list (more time consuption)
# 3. numpy (less memory consume), list(more memory consuption )
# 4. numpy has more functionality than list


In [2]:
import numpy as np

In [ ]:
a=[1,45,89,90]
type (a)

list

In [ ]:
b=np.array(a)
print(b)
type(b)

[ 1 45 89 90]


numpy.ndarray

In [ ]:
c=[[1,2,3],[4,5,6],[7,8,9]]
d=np.array(c)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print("total rows and column", d.shape)
print("total elements", d.size)
print("total dimension", d.ndim)

total rows and column (3, 3)
total elements 9
total dimension 2


In [ ]:
b.ndim

1

In [ ]:
# how to create user define array

a=[]
size= int (input("enter array size: "))
for i in range (size):
  val= int (input ("enter values: "))
  a.append(val)
b=np.array(a)

enter array size: 3
enter values: 3 
enter values: 4
enter values: 5


In [ ]:
b

array([3, 4, 5])

In [ ]:
b*3

array([ 9, 12, 15])

In [ ]:
# pre defined function in python
# 1. zeros()--> it will create an array in which all values will be 0
a=np.zeros(3)
print(a)
b=np.zeros((3,4))
print(b)

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# 2. ones --> it will create an array in which all the values will be 1
a=np.ones(3)
print(a)
b=np.ones((3,4))
print(b)

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 3. eye() --> it will create an array in which the diagonal positional elements value will be one and rest of are zero
a=np.eye(3,3) # it create by default dimension will be 2
a=np.eye(3,3) # it create by default dimension will be 2
# a=np.eye(3,3)  number(rows) == number (column) it means symettric matrix
print(a)
b=np.eye(3,4)     # number(rows) != number (column) it means asymettric matrix
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [3]:
# 4. diag()--> it will create an array that will set diagonal positional custum element by us
a = np.diag([11,2,3,4000]) # it default create symmetric matrix
a

array([[  11,    0,    0,    0],
       [   0,    2,    0,    0],
       [   0,    0,    3,    0],
       [   0,    0,    0, 4000]])

In [19]:
# random module

# a. randint() ----> it will generate random values based on fix criteria
# np.random.randint(min range , max range , total number )
a = np.random.randint(1,10,3)
a

array([8, 3, 6])

In [14]:
# b. rand() ---> it will generate random number from 0 to 1
b = np.random.rand(5)
b

array([0.34163173, 0.34278228, 0.06738266, 0.81922732, 0.25722087])

In [24]:
# c. seed()----> it will fix our random generated data .
np.random.seed(52)
a = np.random.randint(1,10,3)
a

array([6, 8, 7])

In [26]:
# view vs copy
a= np.array([1,20,30,40,50,60])
b=a[2:5]
b[:]=0        # view method can change in real array
b
a

array([ 1, 20,  0,  0,  0, 60])

In [28]:
a= np.array([1,20,30,40,50,60])
b=a[2:5].copy()
b[:]=0              # copy method can't change in real array
b
a

array([ 1, 20, 30, 40, 50, 60])

In [32]:
# reshaping the array
# n(rows)* n(column)=total number of elements
a=np.random.randint(1,50,12)
a

array([43, 12, 28, 36, 36, 34, 36, 34,  6, 17, 12, 49])

In [33]:
a.reshape(2,6)
# can be change in
# 1,12
# 12,1
# 2,6
# 6,2
# 3,4
# 4,3

array([[43, 12, 28, 36, 36, 34],
       [36, 34,  6, 17, 12, 49]])

In [35]:
# condition selection in array
a= np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [37]:
a[a>10]

array([11, 12, 13, 14])

In [38]:
a[a%3==0]

array([ 3,  6,  9, 12])

In [39]:
a=np.array([1,2,3,4])
a**2

array([ 1,  4,  9, 16])

In [40]:
a*2

array([2, 4, 6, 8])

In [41]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [42]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [45]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [47]:
a=np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [48]:
b=np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [49]:
a+b

array([[ 6,  8],
       [10, 12]])

In [50]:
a-b

array([[-4, -4],
       [-4, -4]])

In [52]:
a.dot(b) # for multiply the matrix

array([[19, 22],
       [43, 50]])

In [53]:
# unique method ----> this method return 3 array
# (1). arr --> store unique value
# (2). return_index = True----> in which indexing we have unique values
# (3). return_count = True----> frequency of each element


In [56]:
a=np.array([1,2,5,3,4,2,6,4,2,6,4,6,55,1,5,6,23,5,56,3,6])
a

array([ 1,  2,  5,  3,  4,  2,  6,  4,  2,  6,  4,  6, 55,  1,  5,  6, 23,
        5, 56,  3,  6])

In [57]:
np.unique(a, return_index= True, return_counts= True)

(array([ 1,  2,  3,  4,  5,  6, 23, 55, 56]),
 array([ 0,  1,  3,  4,  2,  6, 16, 12, 18]),
 array([2, 3, 2, 3, 3, 5, 1, 1, 1]))

In [58]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6, 23, 55, 56])

In [59]:
np.unique(a, return_index= False, return_counts= True)

(array([ 1,  2,  3,  4,  5,  6, 23, 55, 56]),
 array([2, 3, 2, 3, 3, 5, 1, 1, 1]))